#@TYPE: Machine
#@NAME: Rock 3A RK3568
#@DESCRIPTION: Rock 3 is a Raspberry Pi 4 Alternative based on Rockchip RK3568 Processor.
#
# NOTE: This machine is for Kernel 5.10 and later. If you are using an older
# kernel, see rock-pi-4.conf

require conf/machine/include/rock-3.inc

KERNEL_DEVICETREE = "rockchip/rk3568-rock-3a.dtb"
UBOOT_MACHINE = "rock-3a-rk3568_defconfig"

PREFERRED_VERSION_u-boot = "radxa"

WKS_FILE = "rock-3a.wks"
MACHINE_EXTRA_RRECOMMENDS = "kernel-modules"
